--- #YAML:1.0
name:                Music-Audioscrobbler-Submit
version:             0.05
abstract:            Module providing routines to submit songs to last.fm using 1.2 protocol.
license:             perl
author:              
    - Edward Allen (ealleniii _at_ cpan _dot_ org)
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Config::Options:               0.01
    Digest::MD5:                   2
    Encode:                        2
    File::Spec:                    3
    IO::File:                      1
    LWP::UserAgent:                2
    Tie::Hash:                     1
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
